apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: node-altair-dev
  region: ap-northeast-1
  version: "1.24"

managedNodeGroups:
  - name: public-workers-dev
    instanceType: t3.medium
    minSize: 2
    desiredCapacity: 3
    maxSize: 4
    availabilityZones: ["ap-northeast-1a", "ap-northeast-1c", "ap-northeast-1d"]
    ssh:
      allow: true
      publicKeyPath: $PUBLIC_WORKERS_PUBLIC_KEY_PATH
  - name: private-workers-dev
    instanceType: t3.medium
    minSize: 2
    desiredCapacity: 3
    maxSize: 4
    availabilityZones: ["ap-northeast-1a", "ap-northeast-1c", "ap-northeast-1d"]
    ssh:
      allow: true
      publicKeyPath: $PRIVATE_WORKERS_PUBLIC_KEY_PATH
    privateNetworking: true
